In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torchxrayvision as xrv
import sys
import numpy as np
import torch
import torchvision
import matplotlib.pyplot as plt
import dataset_utils

In [3]:
model = xrv.baseline_models.xinario.ViewModel()

In [4]:
transform = torchvision.transforms.Compose([
    xrv.datasets.XRayCenterCrop(),
    xrv.datasets.XRayResizer(224)
])
d = dataset_utils.get_data('pc', views='*', transform=transform)

['Granuloma', 'Hemidiaphragm Elevation', 'Pleural_Thickening', 'Nodule', 'Mass', 'Cardiomegaly', 'Consolidation', 'Fibrosis', 'Scoliosis', 'Fracture', 'Atelectasis', 'Emphysema', 'Effusion', 'Air Trapping', 'Aortic Atheromatosis', 'Support Devices', 'Tuberculosis', 'Pneumothorax', 'Costophrenic Angle Blunting', 'Hilar Enlargement', 'Flattened Diaphragm', 'Edema', 'Bronchiectasis', 'Infiltration', 'Tube', 'Aortic Elongation', 'Pneumonia', 'Hernia']


In [5]:
d.csv.view.unique()

array(['PA', 'L', 'AP', 'AP Supine', 'COSTAL', 'UNK', 'EXCLUDE'],
      dtype=object)

In [6]:
frontal = np.where(d.csv.view == 'PA')[0]

In [7]:
lateral = np.where(d.csv.view == 'L')[0]

In [8]:
for i in frontal[:10]:
    img = d[i]['img']
    with torch.no_grad():
        output = model(torch.from_numpy(img))
        print(output, model.targets[output.argmax()])

tensor([[23.1546, 16.9751]]) Frontal
tensor([[23.6190, 15.1804]]) Frontal
tensor([[23.9368, 15.9114]]) Frontal
tensor([[20.4266, 14.5170]]) Frontal
tensor([[25.9273, 14.4245]]) Frontal
tensor([[24.4080, 13.7654]]) Frontal
tensor([[25.0222, 15.7349]]) Frontal
tensor([[23.8637, 16.7607]]) Frontal
tensor([[22.3303, 13.5714]]) Frontal
tensor([[21.2553, 14.0465]]) Frontal


In [9]:
for i in lateral[:10]:
    img = d[i]['img']
    with torch.no_grad():
        output = model(torch.from_numpy(img))
        print(output, model.targets[output.argmax()])

tensor([[17.3186, 26.7156]]) Lateral
tensor([[15.9319, 24.5127]]) Lateral
tensor([[20.1788, 34.1056]]) Lateral
tensor([[20.5084, 35.7469]]) Lateral
tensor([[20.0122, 36.1225]]) Lateral
tensor([[20.1512, 29.6003]]) Lateral
tensor([[21.8098, 32.7101]]) Lateral
tensor([[18.7384, 35.3062]]) Lateral
tensor([[19.8528, 28.8093]]) Lateral
tensor([[20.8488, 33.3455]]) Lateral
